apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: ctfd
spec:
  ports:
    - port: 3306
  selector:
    app: ctfd
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
  labels:
    app: ctfd
spec:
  selector:
    matchLabels:
      app: ctfd
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ctfd
        tier: mysql
    spec:
      containers:
      - image: mariadb:10.4.12
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: ctfd-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ctfd-nfs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ctfd-nfs
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.31
    path: "/home/ctfd"

